spring:
    h2:
        console:
            enabled: true
            path: /h2db
    datasource:
        url: jdbc:h2:mem:permissionsdb;NON_KEYWORDS=USER
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
        initialization-mode: always
        schema: classpath:/static/data.sql
    jpa:
        show-sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
server:
    port: 8081
springdoc:
    enable-native-support: true